### PR TITLE
Add build scripts to simplify the release management

### PR DESCRIPTION
**Pull request by odinserj**
I've added support for Hangfire.Build scripts and configuration for AppVeyor as well. Here are the details about the release management process.

**Change version**
To change a version, run the `build` command as follows:

```
build version
```

The command will prompt for the new version number in `X.Y.Z` format. After changing the version, it will update `appveyor.yml` and `SharedAssemblyInfo.cs` files.

**Publish release**
To make a release version, just create a new release on GitHub with tag in `vX.Y.Z` format (for example, `v0.1.0`). After building, AppVeyor will upload packages (including symbols) to the NuGet feed and upload an archive file with binaries to a GitHub release.

**Publish pre-release**
To make a pre-release version, create a pre-release tag in the format `vX.Y.Z-suffix` (for example, `v0.1.0-beta1`), and AppVeyor will upload pre-release packages instead.

### CODE REVIEW

**Comment by odinserj** [comment]
@barclayadam, I've also -re-added AppVeyor project (it was deleted) – https://ci.appveyor.com/project/odinserj/hangfire-azure-servicebusqueue. Feel free to release versions, I will re-tweet them.

**Comment by barclayadam** [comment]
@odinserj looking good. Can you update the README to fix the build status badge to point to the correct URL? I cannot view it as I only have read-only access to the appveyor project. 

Once that is done this can be merged to master. I'll look at releasing a new version next week once I have this in our prod environment and am happy with it's performance.

**Comment by odinserj** [comment]
Hmm, https://ci.appveyor.com/api/projects/status/3l7dued0cvkjascj?svg=true url from a project settings page returns `{"message":"Build not found or access denied."}` json.

**Comment by odinserj** [comment]
@barclayadam, I've granted some more rights to the GitHub Core team members in AppVeyor.

**Comment by barclayadam** [comment]
Really not sure what the problem is, perhaps some issue with handling of a project with no master branch build yet?

You happy to merge this pull request?

**Comment by odinserj** [comment]
> Really not sure what the problem is, perhaps some issue with handling of a project with no master branch build yet?

You are right, the badge is working now.

> You happy to merge this pull request?

Nothing prevents to do this. I suggest _you_ to push the magic button :smile: :tada:

**Comment by barclayadam** [comment]
Done :tada:

Now shows pending or a broken image (sometimes). I'll keep an eye on it and if not fixed in the next few hours reach our to Appveyor to find and fix the issue.

**Comment by odinserj** [comment]
Yay, thank you! All is fine for me, GitHub caches external images to its own CDN, so the problem may be related to the cache.

image

**Pull request merged**
