### PR TITLE
Servicebus message lock times out after max 5 mins

### PR DESCRIPTION
**Pull request by dersia**
The max timeout someone can put on a message in a servicebus queue is 5 mins. If you're having long-running tasks, this is causing a {{MessageLockLostException}} upon the call of {{message.Complete()}}. To avoid that, this pull request starts a Task which checks every 500 ms if the message lock is about to run out within the next 10 secs, if so it'll renew the lock. This is done until the message is really completed, requeued or disposed.

### CODE REVIEW

**Comment by barclayadam** [comment]
Hey @dersia thanks for the pull request. This has cropped up for me on occasions as well, so glad you have looked in to this.

My only concern is having a background thread created per job executed, it seems a little heavy-handed. 

I'm thinking that perhaps there is a central thread that could be running to manage jobs and renewing their locks.

**Comment by barclayadam** [comment]
Also, it would be better if this pull request was just for the changes to renew the lock, at the moment it also contains the upgrade to 1.5 of Hangfire

**Comment by dersia** [comment]
Hey @barclayadam, I'd share you concerns if this was a Thread. But I choose Task and since I didn't mark this as a LongRunningTaks I hope the TPL is just creating a Task and not a Thread. So this should be ok, I think. ;)

**Comment by barclayadam** [comment]
Ah yeah actually good shout. I only really quickly scanned this, have not reviewed it in any more real detail than that. I'll try and get to this sometime soon as it would be helpful for our own usage as well

**Comment by dersia** [comment]
hi @barclayadam, what about this fix? This is causing issues and our Logs are full of Exceptions.

**Comment by barclayadam** [comment]
Version 2.2.0 has been released with keep alive code.

**Pull request closed without merging**
